global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['broker:7071']

  - job_name: 'producer'
    static_configs:
      - targets: ['producer:8000']

